name: fake_process_manager
description: Process Manager for faking processes in tests. Taken from Flutter Tools.
version: 0.1.0+1
homepage: https://github.com/mmcc007/fake_process_manager
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  process: ^4.0.0
  tool_base:
    git: https://github.com/ventskus-roman/tool_base
  mockito: ^4.1.4
  test: ^1.16.5
dev_dependencies:
  pedantic: ^1.7.0
  tool_base_test:
    git: https://github.com/ventskus-roman/tool_base_test